language: php
dist: xenial
cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files

services:
  - mysql

matrix:
  include:
    - php: 7.3
  fast_finish: true
addons:
  apt:
    packages:
      - nginx
      - realpath
install:
  - composer install
  - npm install
  #- travis/install-nginx.sh
  - echo '[mysqld]' | sudo sh -c 'cat >>  /etc/mysql/conf.d/travis.cnf'
  - echo 'innodb_file_format=Barracuda' | sudo sh -c 'cat >>  /etc/mysql/conf.d/travis.cnf'
  - echo 'innodb_file_per_table=1' | sudo sh -c 'cat >>  /etc/mysql/conf.d/travis.cnf'
  - echo 'innodb_large_prefix=1' | sudo sh -c 'cat >>  /etc/mysql/conf.d/travis.cnf'
  - sudo service mysql restart
  - scripts/patchdb.sh -t . -d $DB_NAME -u root -i
  - php -S 127.0.0.1:8080 -t src/public index.php &

env:
  global:
    - JOINDIN_API_BASE_URL=http://127.0.0.1:8080
    - DB_NAME=joindin
    - MYSQL_HOST=127.0.0.1
    - MYSQL_USER=root
    - MYSQL_PASSWORD=''

before_install:
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -u root

before_script:
  - cp src/config.php.dist src/config.php
  - cp src/database.php.dist src/database.php
  - git remote set-branches --add origin master
  - git fetch

script:
  - ./node_modules/.bin/jasmine-node tests/frisby/api_spec.js
  - composer check
