language: php
dist: trusty
cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files

services:
  - mysql

matrix:
  include:
    - php: 7.3
  fast_finish: true
addons:
  apt:
    packages:
      - nginx
      - realpath
install:
  - composer install
  - npm install
  - travis/install-nginx.sh
  - scripts/patchdb.sh -t . -d $DB_NAME -u root -i

env:
  global:
    - JOINDIN_API_BASE_URL=http://joindin-api.localhost
    - DB_NAME=joindin

before_install:
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -u root

before_script:
  - cp src/config.php.dist src/config.php
  - git remote set-branches --add origin master
  - git fetch

script:
  - composer check
  - ./node_modules/.bin/jasmine-node tests/frisby/api_spec.js
